# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import simplemde.fields


class Migration(migrations.Migration):

    replaces = [('galleries', '0001_initial'), ('galleries', '0002_auto_20170130_1723'), ('galleries', '0003_auto_20170318_2010'), ('galleries', '0004_auto_20170429_1513'), ('galleries', '0005_auto_20170429_1600'), ('galleries', '0006_auto_20170429_1734'), ('galleries', '0007_auto_20170429_2027'), ('galleries', '0008_auto_20170429_2225'), ('galleries', '0009_portfolio_blurb'), ('galleries', '0010_auto_20170501_2211')]

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('abstract', simplemde.fields.SimpleMDEField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnail')),
            ],
            options={
                'verbose_name_plural': 'galleries',
                'verbose_name': 'gallery',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True, max_length=200, null=True)),
                ('extra', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='full')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnail')),
                ('link', models.URLField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('external-video', 'Video')], default='image', max_length=100)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
                'verbose_name_plural': 'media items',
                'verbose_name': 'media',
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Media')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
                'verbose_name_plural': 'gallery media',
                'verbose_name': 'gallery media',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('blurb', simplemde.fields.SimpleMDEField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'portfolios',
                'verbose_name': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Portfolio')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
                'verbose_name_plural': 'portfolio galleries',
                'verbose_name': 'portfolio gallery',
            },
        ),
    ]
