# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_squashed_0010_auto_20170501_2211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'media', 'verbose_name_plural': 'media items'},
        ),
    ]
