# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Galleries'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'Media', 'verbose_name_plural': 'Media items'},
        ),
        migrations.AddField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('external-video', 'Video')], default='image', max_length=100),
        ),
    ]
