# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20170130_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
