# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20170501_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerymedia',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='portfoliogallery',
            name='sort_order',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='Sort'),
        ),
    ]
