# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 22:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('galleries', '0003_auto_20170318_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'verbose_name': 'gallery media',
                'verbose_name_plural': 'gallery media',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='PortfolioGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
                'verbose_name': 'portfolio gallery',
                'verbose_name_plural': 'portfolio galleries',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'gallery', 'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'media', 'verbose_name_plural': 'media items'},
        ),
        migrations.RemoveField(
            model_name='media',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='media',
            name='sort_order',
        ),
        migrations.AddField(
            model_name='portfoliogallery',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
        ),
        migrations.AddField(
            model_name='portfoliogallery',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Portfolio'),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Media'),
        ),
    ]
