# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20170502_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='revision',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
