# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20170429_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
