# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:20
from __future__ import unicode_literals

from django.db import migrations, models


def unset_missing_images(apps, schema_editor):
    Media = apps.get_model('galleries', 'Media')
    for media in Media.objects.iterator():
        try:
            if media.image:
                _name = media.image.file.name
        except FileNotFoundError:
            media.image = None
            media.save()

        try:
            if media.thumbnail:
                _name = media.thumbnail.file.name
        except FileNotFoundError:
            media.thumbnail = None
            media.save()

    Gallery = apps.get_model('galleries', 'Gallery')
    for gallery in Gallery.objects.iterator():
        try:
            if gallery.thumbnail:
                _name = gallery.thumbnail.file.name
        except FileNotFoundError:
            gallery.thumbnail = None
            gallery.save()


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20170502_1618'),
    ]

    operations = [
        migrations.RunPython(unset_missing_images, migrations.RunPython.noop),
        migrations.AddField(
            model_name='media',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', upload_to='full', width_field='image_width'),
        ),
    ]
