# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 05:23
from __future__ import unicode_literals

from django.db import migrations


# Save all Media records again to update their width and height fields


def refresh_all_media_records(apps, schema_editor):
    Media = apps.get_model('galleries', 'Media')
    for media in Media.objects.iterator():
        try:
            media.save()
        except FileNotFoundError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_auto_20170502_2220'),
    ]

    operations = [
        migrations.RunPython(refresh_all_media_records, migrations.RunPython.noop),
    ]
