# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_refresh_all_media_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
