# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 22:28
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0008_auto_20170429_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='blurb',
            field=markdownx.models.MarkdownxField(blank=True, null=True),
        ),
    ]
