# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_auto_20170505_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='synopsis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
