# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 05:11
from __future__ import unicode_literals

from django.db import migrations
import simplemde.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0009_portfolio_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='abstract',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='blurb',
            field=simplemde.fields.SimpleMDEField(blank=True, null=True),
        ),
    ]
