# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0010_auto_20170509_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'verbose_name': 'media', 'verbose_name_plural': 'images and videos'},
        ),
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(),
        ),
    ]
