# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0011_auto_20181025_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='theme_id',
            field=models.CharField(choices=[('stuartmccall_ca', 'stuartmccall.ca'), ('northlightimages_com', 'northlightimages.com')], default='stuartmccall_ca', max_length=50),
            preserve_default=False,
        ),
    ]
