# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0012_portfolio_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='theme_id',
            field=models.CharField(choices=[('stuartmccall_ca', 'stuartmccall.ca'), ('northlightimages_com', 'northlightimages.com')], max_length=50, verbose_name='theme'),
        ),
    ]
