# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 05:59
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify


def slugify_portfolio_title(apps, schema_editor):
    Portfolio = apps.get_model('galleries', 'Portfolio')
    for portfolio in Portfolio.objects.all():
        portfolio.slug = slugify(portfolio.title)
        portfolio.save()


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0014_portfolio_slug'),
    ]

    operations = [
        migrations.RunPython(
            slugify_portfolio_title,
            migrations.RunPython.noop
        ),
    ]
