# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-30 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0015_auto_20181229_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='slug',
            field=models.SlugField(),
        ),
    ]
