# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0016_auto_20181229_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, db_index=True, verbose_name='Sort')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Media')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Portfolio')),
            ],
            options={
                'verbose_name': 'portfolio media',
                'verbose_name_plural': 'portfolio media',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
