# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 23:02
from __future__ import unicode_literals

from django.db import migrations


def migrate_portfolio_gallery_to_portfolio_media(apps, schema_editor):
    Portfolio = apps.get_model('galleries', 'Portfolio')
    Gallery = apps.get_model('galleries', 'Gallery')
    PortfolioGallery = apps.get_model('galleries', 'PortfolioGallery')
    GalleryMedia = apps.get_model('galleries', 'GalleryMedia')
    PortfolioMedia = apps.get_model('galleries', 'PortfolioMedia')

    for portfolio in Portfolio.objects.all():
        sort_order = 0
        for portfolio_gallery in portfolio.portfoliogallery_set.order_by('sort_order'):
            portfolio = portfolio_gallery.portfolio
            gallery = portfolio_gallery.gallery
            for gallery_media in gallery.gallerymedia_set.order_by('sort_order'):
                media = gallery_media.media
                sort_order += 1
                portfolio_media = PortfolioMedia(
                    sort_order=sort_order,
                    portfolio=portfolio,
                    gallery=gallery,
                    media=media
                )
                portfolio_media.save()


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0017_portfoliomedia'),
    ]

    operations = [
        migrations.RunPython(
            migrate_portfolio_gallery_to_portfolio_media,
            migrations.RunPython.noop
        ),
    ]
