# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-05 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0018_auto_20190104_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerymedia',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='gallerymedia',
            name='media',
        ),
        migrations.DeleteModel(
            name='GalleryMedia',
        ),
    ]
