# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-06 22:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0019_auto_20190104_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliogallery',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 6, 22, 10, 10, 654902, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliogallery',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 6, 22, 10, 21, 982980, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliomedia',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
