# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 07:02
from __future__ import unicode_literals

from django.db import migrations


def migrate_portfoliogallery_to_gallery(apps, schema_editor):
    Gallery = apps.get_model('galleries', 'Gallery')
    PortfolioGallery = apps.get_model('galleries', 'PortfolioGallery')

    galleries_touched = set()

    for portfoliogallery in PortfolioGallery.objects.all():
        gallery = portfoliogallery.gallery
        if gallery.pk in galleries_touched:
            # We will make a new copy of this gallery
            gallery.pk = None
        else:
            galleries_touched.add(gallery.pk)
        gallery.portfolio = portfoliogallery.portfolio
        gallery.sort_order = portfoliogallery.sort_order
        gallery.save()


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0021_auto_20190108_2252'),
    ]

    operations = [
        migrations.RunPython(
            migrate_portfoliogallery_to_gallery,
            migrations.RunPython.noop
        ),
    ]
