# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0022_auto_20190108_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliogallery',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='portfoliogallery',
            name='portfolio',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='sort_order',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Sort'),
        ),
        migrations.DeleteModel(
            name='PortfolioGallery',
        ),
    ]
