# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-13 00:18
from __future__ import unicode_literals

from django.db import migrations
import sort_order_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0023_auto_20190109_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort'),
        ),
        migrations.AlterField(
            model_name='portfoliomedia',
            name='sort_order',
            field=sort_order_field.fields.SortOrderField(db_index=True, default=0, verbose_name='Sort'),
        ),
    ]
