# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-25 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0026_auto_20190114_2319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gallery',
            unique_together=set([]),
        ),
    ]
