# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-19 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0027_auto_20190125_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
