# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-23 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0028_portfolio_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='meta_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
