# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(max_length=100)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='sites.Site')),
            ],
            options={
                'verbose_name': 'google analytics tracking code',
                'verbose_name_plural': 'google analytics tracking codes',
            },
        ),
    ]
